
from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from PySide6 import QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(641, 410)
        MainWindow.setMinimumSize(QSize(641, 410))
        MainWindow.setMaximumSize(QSize(641, 410))
        icon = QIcon()
        icon.addFile(u"../imgs/logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionNew_File = QAction(MainWindow)
        self.actionNew_File.setObjectName(u"actionNew_File")
        self.actionOpen_File_2 = QAction(MainWindow)
        self.actionOpen_File_2.setObjectName(u"actionOpen_File_2")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setShortcut('Ctrl + S')
        self.actionLight = QAction(MainWindow)
        self.actionLight.setObjectName(u"actionLight")
        self.actionDark = QAction(MainWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.actionGitHub = QAction(MainWindow)
        self.actionGitHub.setObjectName(u"actionGitHub")
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(450, 160, 111, 21))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(40, 326, 110, 29))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(121, 66, 110, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 96, 321, 211))
        self.label_3.setStyleSheet(u"")
        self.label_3.setPixmap(QPixmap(u"imgs/grey.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.comboBox = QComboBox(self.centralwidget)

        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(370, 190, 260, 29))
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMaximum(9999)
        self.spinBox.setGeometry(QRect(130, 16, 71, 30))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 121, 21))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(200, 326, 110, 29))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(270, 4, 131, 51))
        self.label_5.setPixmap(QPixmap(u"imgs/logo.png"))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-10, 50, 651, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 641, 24))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuInfo = QMenu(self.menubar)
        self.menuInfo.setObjectName(u"menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuInfo.addAction(self.actionGitHub)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"nGIF", None))
        self.actionNew_File.setText(QCoreApplication.translate("MainWindow", u"New File", None))
        self.actionOpen_File_2.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionLight.setText(QCoreApplication.translate("MainWindow", u"Light", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.actionGitHub.setText(QCoreApplication.translate("MainWindow", u"GitHub", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Elements list", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Add mediafile", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Current image", None))
        self.label_3.setText("")

        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Frames duration:", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Del mediafile", None))
        self.label_5.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuInfo.setTitle(QCoreApplication.translate("MainWindow", u"Info", None))
